name: Compile-Check

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup-Java
      uses: actions/setup-java@v2
      with:
        java-version: '8'

    - name: Build-with-Maven
      run: mvn -B clean package

    - name: Check-if-branch-can-be-compiled
      run: |
        if [[ $? -ne 0 ]]; then
          echo "Error: Branch cannot be compiled."
          exit 1
        fi

    - name: Merge-Branch
      if: success()
      run: |
        echo "Branch can be compiled. Merging now."
        git merge --no-ff ${{ github.head_ref }}>
